name: multichecker

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  statictest:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup multichecker binary
        run: make build-staticlint

      - name: Run multichecker
        run: make run-staticlint-with-ignore-tests
