name: protobuf

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1